<?xml version="1.0"?>
<package format="3">
  <name>kafeiche_webrtc_cam</name>
  <version>0.1.0</version>
  <description>WebRTC video streaming from libcamera using GStreamer</description>

  <maintainer email="you@example.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>rclcpp</build_depend>
  <build_depend>libgstreamer1.0-dev</build_depend>
  <build_depend>libgstreamer-plugins-base1.0-dev</build_depend>
  <build_depend>libgstreamer-plugins-bad1.0-dev</build_depend>

  <!-- GStreamer is external, not rosdep -->
  <exec_depend>rclcpp</exec_depend>
  <exec_depend>gstreamer1.0</exec_depend>
  <exec_depend>gstreamer1.0-plugins-base</exec_depend>
  <exec_depend>gstreamer1.0-plugins-bad</exec_depend>
  <exec_depend>gstreamer1.0-plugins-good</exec_depend>
  <exec_depend>ros2launch</exec_depend>



</package>
