controller_manager:
  ros__parameters:
    update_rate: 30 

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    diff_controller:
      type: diff_drive_controller/DiffDriveController

diff_controller:
  ros__parameters:

    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    
    use_stamped_vel: false

    wheel_separation: 0.28974
    wheel_radius: 0.07504

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    position_feedback: true 
    enable_odom_tf: false
    
    cmd_vel_timeout: 0.5
    publish_limited_velocity: false

    linear.x.max_velocity: 0.60 # m/s
    linear.x.min_velocity: -0.60
    linear.x.max_acceleration: 0.3
    linear.x.max_deceleration: -0.3

    angular.z.max_velocity: 3.0 # rad/s
    angular.z.min_velocity: -3.0
    angular.z.max_acceleration: 1.5
    angular.z.max_deceleration: -1.5

    # linear.x.max_jerk: 2.0
    # linear.x.min_jerk: -2.0
    # angular.z.max_jerk: 10.0
    # angular.z.min_jerk: -10.0